name: travel-booking-package

services:

  mysql:
    image: mysql:8.0
    container_name: travel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel_booking_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: mjayashree08/travel-booking-backend:latest
    container_name: travel-backend
    environment:
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    image: mjayashree08/travel-booking-frontend:latest
    container_name: travel-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  mysql_data: